# Generated by Django 4.2.4 on 2023-09-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAFFOOD', '0006_menu_food_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
