# Generated by Django 4.2.4 on 2023-09-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAFFOOD', '0008_workingdays_food_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
